// 5-NG/1-shop-ui/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  products: Array<any> = [
    {
      id: 1,
      name: 'Laptop',
      price: 198000,
      image: 'images/Laptop.png',
      description: 'New Mac Pro',
      canBuy: true
    },
    {
      id: 2,
      name: 'Mobile',
      price: 18000,
      image: 'images/Mobile.png',
      description: 'New  Pro',
      canBuy: true
    }
  ]

 

}

<div class="container">

  <nav class="navbar navbar-light bg-primary">
    <a class="navbar-brand" href="#">online-shopping</a>
  </nav>

  <hr />
  <hr />

  <div *ngFor="let product of products" class="list-group-item">
    <div class="row">
      <div class="col-3 col-sm-3 col-md-3">
        <!-- <img src="{{product.image}}" class="img-fluid" /> -->
        <img [src]="product.image" class="img-fluid" />
      </div>
      <div class="col-9 col-sm-9 col-md-9">
        <h5>{{product.name}}</h5>
        <h6>{{product.price}}</h6>
        <button *ngIf="product.canBuy" class="btn btn-primary">buy</button>
        <hr />
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a (click)="changeTab(1)" class="nav-link" [class.active]="isTabSelected(1)" href="#">Description</a>
          </li>
          <li class="nav-item">
            <a (click)="changeTab(2)" [ngClass]="{'nav-link':true,active:isTabSelected(2)}" href="#">Specification</a>
          </li>
          <li class="nav-item">
            <a (click)="changeTab(3)" [ngClass]="{'nav-link':true,active:isTabSelected(3)}" href="#">Reviews</a>
          </li>
        </ul>
        <div *ngIf="isTabSelected(1)">{{product.description}}</div>
        <div *ngIf="isTabSelected(2)">Not Yet</div>
        <div *ngIf="isTabSelected(3)">None Yet</div>
      </div>
    </div>
  </div>

</div>

// 2-UI/1-React/4-online-shop-ui-v1/src/App.js
import React, { Component } from 'react';
import './App.css';
import Navbar from './components/Navbar';
import 'bootstrap/dist/css/bootstrap.css'
import classNames from 'classnames'

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      currentTab: 1,
      products: [
        {
          id: 111,
          name: 'Laptop',
          price: 198000.00,
          canBuy: true,
          image: 'images/Laptop.png',
          description: 'New Mac pro'
        },
        {
          id: 222,
          name: 'Mobile',
          price: 18000.00,
          canBuy: true,
          image: 'images/Mobile.png',
          description: 'New Mac pro'
        },
      ]
    }
  }
  changeTab(tabIndex) {
    this.setState({ currentTab: tabIndex })
  }
  renderBuyBtn(product) {
    if (product.canBuy) return <button className="btn btn-sm btn-primary">buy</button>
    else return null;
  }
  renderTabPanel(item) {
    let { currentTab } = this.state;
    let panel;
    switch (currentTab) {
      case 1: {
        panel = (<div>{item.description}</div>)
        break;
      }
      case 2: {
        panel = (<div>Not Yet</div>)
        break;
      }
      case 3: {
        panel = (<div>None Yet</div>)
        break;
      }
      default: panel = null;
    }
    return panel;
  }
  renderProducts() {
    let { products, currentTab } = this.state;
    return products.map((item, idx) => {
      return (
        <div key={idx} className="list-group-item">
          <div className="row">
            <div className="col-3 col-sm-3 col-md-3">
              <img src={item.image} className="img-fluid" alt={item.name} />
            </div>
            <div className="col-9 col-sm-9 col-md-9">
              <h5>{item.name}</h5>
              <h6>&#8377;{item.price}</h6>
              {this.renderBuyBtn(item)}
              <ul className="nav nav-tabs">
                <li className="nav-item">
                  <a onClick={e => this.changeTab(1)} className={classNames('nav-link', { active: currentTab === 1 })} href="#/">Description</a>
                </li>
                <li className="nav-item">
                  <a onClick={e => this.changeTab(2)} className={classNames('nav-link', { active: currentTab === 2 })} href="#/">Specifcation</a>
                </li>
                <li className="nav-item">
                  <a onClick={e => this.changeTab(3)} className={classNames('nav-link', { active: currentTab === 3 })} href="#/">Reviews</a>
                </li>
              </ul>
              {this.renderTabPanel(item)}
            </div>
          </div>
        </div>
      )
    })
  }
  render() {
    return (
      <div className="container">
        <Navbar title="online-shop" />
        <hr />
        <hr />

        {this.renderProducts()}

      </div>
    );
  }
}

export default App;
